version: '3.9'

include:
  - compose.collector.yaml
  - compose.tracing.yaml

services:
  reference-api:
    container_name: reference-api
    image: reference-api:latest
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: . # replace with the actual name of your project
      dockerfile: Jobs.ReferenceApi/Dockerfile
    ports:
      - 7007:7007
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=DockerCert
      - ASPNETCORE_URLS=https://+:7007
      #- ASPNETCORE_HTTPS_PORT=7007
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=dfvgbh
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetcore.pfx
    volumes:
      - ~/.microsoft/usersecrets/:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro

  company-api:
    container_name: company-api
    image: company-api:latest
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: . # replace with the actual name of your project
      dockerfile: Jobs.CompanyApi/Dockerfile
    ports:
      - 7057:7057
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=DockerCert
      - ASPNETCORE_URLS=https://+:7057
      #- ASPNETCORE_HTTPS_PORT=7007
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=dfvgbh
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetcore.pfx
    volumes:
      - ~/.microsoft/usersecrets/:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro

  account-api:
    container_name: account-api
    image: account-api:latest
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: . # replace with the actual name of your project
      dockerfile: Jobs.AccountApi/Dockerfile
    ports:
      - 7161:7161
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=DockerCert
      - ASPNETCORE_URLS=https://+:7161
      #- ASPNETCORE_HTTPS_PORT=7007
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=dfvgbh
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetcore.pfx
    volumes:
      - ~/.microsoft/usersecrets/:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro

  vacancy-api:
    container_name: vacancy-api
    image: vacancy-api:latest
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: . # replace with the actual name of your project
      dockerfile: Jobs.VacancyApi/Dockerfile # Dockerfile 1 alpine linux with certs
    ports:
      - 7114:7114
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCert
      - ASPNETCORE_URLS=https://+:7114
      - ASPNETCORE_HTTPS_PORT=7114
    volumes:
      - ~/.microsoft/usersecrets/:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro
      #- ./dev-cert:/dev-cert:ro

    #networks:
      #- practical-otel-net

  gateway-api:
    container_name: gateway-api
    image: gateway-api:latest
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: . # replace with the actual name of your project
      dockerfile: Jobs.YarpGateway/Dockerfile
    ports:
      - 7046:7046
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=DockerCert
      - ASPNETCORE_URLS=https://+:7046
      #- ASPNETCORE_HTTPS_PORT=7007
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=dfvgbh
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetcore.pfx
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/dev-cert/server.cert.pem
      #- ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/dev-cert/server.key.pem
    volumes:
      - ~/.microsoft/usersecrets/:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro
      - ./dev-cert:/dev-cert:ro

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - 8500:8500 # Exposing HTTP API (optional, for non-secure access)
      - 8501:8501 # Exposing HTTPS API
      #- 8501:8501 # HTTPS API port
      #- 8301:8301 # Serf LAN
      #- 8301:8301/udp # Serf LAN UDP
    environment:
      CONSUL_LOCAL_CONFIG: |
        {
          "server": true, 
          "bootstrap_expect": 1, 
          "data_dir": "/consul/data", 
          "tls": {
              "defaults": {
                 "verify_incoming": false, 
                 "verify_outgoing": false
              }, 
              "https": {
                 "cert_file": "/consul/config/certs/consul.crt", 
                 "key_file": "/consul/config/certs/consul.key"
              }
          },
          "ports": {
             "https": 8501
          }
        }
  #    - CONSUL_LOCAL_CONFIG={"server": true, "bootstrap_expect": 1, "data_dir": "/consul/data", "tls": {"defaults": {"verify_incoming": true, "verify_outgoing": true}, "https": {"port": 8501, "cert_file": "/consul/config/certs/consul.crt", "key_file": "/consul/config/certs/consul.key"}, "ca_file": "/consul/config/certs/ca.crt"}}}
   # "port": 8500, "ca_file": "/consul/config/certs/ca.crt"
    volumes:
      - ./consul/certs:/consul/config/certs # Mount your certs directory

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    ports:
      - 8200:8200
      - 8201:8201
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=https://127.0.0.1:8200
      - VAULT_API_ADDR=https://127.0.0.1:8200
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${HOME}/vault/logs:/vault/logs/:rw
      - ${HOME}/vault/data:/vault/data/:rw
      - ${HOME}/vault/config:/vault/config/:rw
      - ${HOME}/vault/certs:/vault/certs/:rw
      - ${HOME}/vault/file:/vault/file/:rw
      - ${HOME}/vault/pki:/vault/pki
      #- ./vault/pki:/vault/pki
      #- /home/jupiter/volumes/vault/:/vault/:rw
    healthcheck:
      retries: 5
    command: vault server -config=/vault/config/configcert.hcl
    #networks:
    #  - practical-otel-net

  vault-init:
   image: hashicorp/vault:latest
   container_name: localsetup-vault-init
   command:
     - "sh"
     - "-c"
     - "chmod 755 /vault/scripts/vault-init-cert.sh && /vault/scripts/vault-init-cert.sh"
   environment:
     VAULT_ADDR: https://vault:8200
     VAULT_CACERT: /vault/certs/server.vault.crt
     #VAULT_CLIENT_CERT: /vault/certs/server.vault.crt
     #VAULT_CLIENT_KEY: /vault/certs/server.vault.key
     #VAULT_ADDR: https://localhost:8200
   volumes:
     - ${HOME}/vault/scripts/:/vault/scripts/
     - ${HOME}/vault/pki:/vault/pki
     - ${HOME}/vault/certs:/vault/certs
   depends_on:
     vault:
       condition: service_started
   #networks:
     #- practical-otel-net

  postgres:
    container_name: postgres-db
    image: postgres:16-alpine
    ports:
      # - "127.0.0.1:5432:5432"
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
       - POSTGRES_PASSWORD=newpwd
       - POSTGRES_USER=admin
       #- POSTGRES_DB=postgres
    networks:
      #- postgres
      - practical-otel-net

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      command: start-dev --http-port=9009
      #entrypoint: /opt/keycloak/bin/kc.sh start-dev --hostname-strict=false --features=hostname:v1 --hostname-port=8086
      environment:
        KC_DB : postgres
        #KC_DB_URL: postgres-db
        KC_DB_URL_HOST: postgres-db
        KC_DB_URL_DATABASE: keycloak
        KC_DB_USERNAME: admin
        KC_DB_PASSWORD: newpwd
        KC_DB_SCHEMA: public
        KC_HEALTH_ENABLED: true
        KC_METRICS_ENABLED: true
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: newpwd
      ports:
        - 9003:9000
        - 9001:9009
      networks:
        - practical-otel-net
      depends_on:
        - postgres

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config-files/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.listen-address=:8080'
    ports:
      - "8081:8080"
    environment:
      - config.file=/etc/prometheus/prometheus.yml
    networks:
      - practical-otel-net

  loki:
    image: grafana/loki:latest
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    networks:
      - practical-otel-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./config-files/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - zipkin
      - prometheus
      - loki
      - collector
    networks:
      - practical-otel-net

networks:
  practical-otel-net:
    name: practical-otel-net
    driver: bridge

volumes:
  cache:
    driver: local

